//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinica
    {
        public int idClinica { get; set; }
        public string nombreClinica { get; set; }
        public string direccionClinica { get; set; }
        public Nullable<int> clihabilitado { get; set; }
    }
}
